apiVersion: v1
kind: Service
metadata:
  name: optimize
  labels:
    app: optimize
spec:
  type: NodePort
  ports:
    - port: 5000
      name: http
  selector:
    app: optimize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: optimize-api-config
data:
  apiUrl: "http://marketdata:8080/v1/marketdata"
---
apiVersion: v1
kind: Secret
metadata:
  name: optimize-api-key
data:
  apiKey: "MTIzNDU="
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: optimize-deployment
  labels:
    app: optimize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimize
  template:
    metadata:
      labels:
        app: optimize
    spec:
      containers:
      - image: optimize:veronikasp
        imagePullPolicy: Never
        name: optimize
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: optimize-api-config
              key: apiUrl
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: optimize-api-key
              key: apiKey
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 30